### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by PLUCS2** [robbal5/Wanderlust#2]
- [ ] What is the address_id for on the Users table? 
- [ ] Lets chat about addresses - the table setup you have makes it good for search and ease of lookup, but the google maps API works the most easily with a latitude and longitude 
- [ ] You likely want more information on your Properties table (number of bedrooms, number of bathrooms, etc.) 
- [ ] You  likely want to have an amenities table as well (see airBnB site) 
- [ ] For the photos you will use AWS - the table looks kind of similar to what is listed in your schema (it has the property_id and some other information). That said, for now that table is fine the way it is - we can discuss further when you get to your Properties MVP 

Nice work! This looks great so far - let me know if you have any questions

**Comment by robbal5** [comment]
1) I see on Airbnb's profile section there's a spot to put an optional address for the user. I was thinking if I had time for a bonus, my home page could have links to popular destinations close to the user's saved address. Other than that, I didn't have much of a plan for that data.

2) That makes a lot of sense, I have added latitude and longitude to the address table as well. 

3) I have added several pieces of information to the Properties table after looking at the site again, including some that you called out above.

4) I have added an Amenities table and a Property Amenities joins table to handle this.

5) Understood. Is AWS something we'll be going over in an official capacity, or is that something dependent on self research?
