### ISSUE TITLE
Sample State & Routes

### ISSUE THREAD

**Issue by PLUCS2** [robbal5/Wanderlust#3]
- [ ] Where is the information in your Arrays in the sessions slice of state coming from? 

## Routes 
Nice work! These look great! 

Let me know if you have any questions!

**Comment by robbal5** [comment]
For those arrays, I was thinking I could potentially use them in a bonus display if I had time. The recent city searches would appear in a dropdown below the search bar when the user clicks on it. This array would be populated in when the SEARCH action type is dispatched. The sessions reducer would have a corresponding case in the reducer where the city id being searched, which will be included in the payload returned from Rails, will be pushed into the array. There will also be a corresponding action for the Logout action type where this array will be emptied.

Similarly when a user selects a property to view, a request for additional information on that property including reviews, reservations, etc will be sent to the server. The session reducer will have a corresponding case where the property_id will be pushed into this array. I was thinking I could create an index on the home page that displays recently viewed properties IF this array has a length greater than one. If not, it would just render null. Similar to the city searches, this array would clear out at time of logout. 

Please let me know if this makes sense or if you have any additional questions. Thanks!
